class EjercicioMaestro {
  final String nombre;
  final String grupoMuscular;

  const EjercicioMaestro({
    required this.nombre,
    required this.grupoMuscular,
  });
}

const List<EjercicioMaestro> LISTA_EJERCICIOS_MAESTRA = [
  // PECHO
  EjercicioMaestro(nombre: 'Press de Banca Plano con Barra', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Press de Banca Plano con Mancuernas', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Press Inclinado con Barra', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Press Inclinado con Mancuernas', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Press Inclinado en Multipower', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Press Declinado con Barra', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Press Declinado con Mancuernas', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Press en Máquina Hammer', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Press Horizontal en Máquina', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Aperturas con Mancuernas', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Aperturas en Peck Deck', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Cruce de Poleas Altas', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Cruce de Poleas Bajas', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Cruce de Poleas Medias', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Fondos para Pecho', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Flexiones de Pecho', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Pullover con Mancuerna', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Pullover en Polea', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Press en Máquina Convergente', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Press Unilateral en Máquina', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Press de Pecho Sentado', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Press Inclinado en Máquina', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Press Declinado en Máquina', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Aperturas en Polea', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Press Guillotina', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Press con Agarre Cerrado', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Press de Pecho en Smith', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Press Alternado con Mancuernas', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Aperturas Inclinado con Mancuernas', grupoMuscular: 'Pecho'),
  EjercicioMaestro(nombre: 'Fondos Asistidos', grupoMuscular: 'Pecho'),

  // ESPALDA
  EjercicioMaestro(nombre: 'Dominadas Pronadas', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Dominadas Supinas', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Dominadas Neutras', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Jalón al Pecho', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Jalón Tras Nuca', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Jalón con Agarre Cerrado', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Jalón con Agarre Abierto', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Jalón Unilateral', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Remo con Barra', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Remo Pendlay', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Remo con Mancuerna', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Remo en Máquina Hammer', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Remo Sentado en Polea', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Remo con Agarre Cerrado', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Remo T-Bar', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Remo en Punta', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Remo en Multipower', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Pullover en Polea', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Peso Muerto Convencional', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Peso Muerto Rumano', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Rack Pull', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Hiperextensiones', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Buenos Días', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Remo Unilateral en Polea', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Jalón con Barra V', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Jalón con Cuerda', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Remo Bajo en Polea', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Face Pull', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Dominadas Asistidas', grupoMuscular: 'Espalda'),
  EjercicioMaestro(nombre: 'Pulldown en Máquina', grupoMuscular: 'Espalda'),

  // HOMBRO
  EjercicioMaestro(nombre: 'Press Militar con Barra', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Press Militar con Mancuernas', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Press Arnold', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Press Militar en Multipower', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Press de Hombro en Máquina', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Elevaciones Laterales con Mancuernas', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Elevaciones Laterales en Polea', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Elevaciones Laterales en Máquina', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Elevaciones Frontales con Barra', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Elevaciones Frontales con Mancuernas', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Elevaciones Frontales en Polea', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Pájaros con Mancuernas', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Pájaros en Peck Deck', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Face Pull Hombro', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Remo al Mentón con Barra', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Remo al Mentón en Polea', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Press Tras Nuca', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Press Unilateral con Mancuerna', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Press Unilateral en Máquina', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Elevaciones Laterales Unilaterales', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Elevaciones Laterales Sentado', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Elevaciones Laterales Inclinado', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Elevaciones Frontales con Disco', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Press Push Press', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Press con Kettlebell', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Press de Hombro Hammer', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Encogimientos con Barra', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Encogimientos con Mancuernas', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Press Viking', grupoMuscular: 'Hombro'),
  EjercicioMaestro(nombre: 'Reverse Pec Deck', grupoMuscular: 'Hombro'),

  // TRÍCEPS
  EjercicioMaestro(nombre: 'Extensión de Tríceps en Polea', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Extensión de Tríceps con Cuerda', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Extensión de Tríceps con Barra Recta', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Extensión de Tríceps con Barra V', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Press Francés con Barra', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Press Francés con Mancuernas', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Press Francés EZ', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Rompecráneos', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Fondos para Tríceps', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Fondos Asistidos Tríceps', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Press Cerrado con Barra', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Press Cerrado en Multipower', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Patada de Tríceps con Mancuerna', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Patada de Tríceps en Polea', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Extensión Unilateral en Polea', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Extensión por Encima de la Cabeza', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Extensión con Mancuerna a Dos Manos', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Extensión con Cuerda Sobre Cabeza', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Extensión con Barra Sobre Cabeza', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Press JM', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Press Tate', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Extensión en Máquina', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Fondos en Banco', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Flexiones Diamante', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Extensión Inversa en Polea', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Tríceps en Polea Inversa', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Press de Tríceps Hammer', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Extensión Sentado con Mancuerna', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Dips con Peso', grupoMuscular: 'Tríceps'),
  EjercicioMaestro(nombre: 'Press de Tríceps en Máquina', grupoMuscular: 'Tríceps'),

  // BÍCEPS
  EjercicioMaestro(nombre: 'Curl con Barra', grupoMuscular: 'Bíceps'),
  EjercicioMaestro(nombre: 'Curl con Barra EZ', grupoMuscular: 'Bíceps'),
  EjercicioMaestro(nombre: 'Curl con Mancuernas', grupoMuscular: 'Bíceps'),
  EjercicioMaestro(nombre: 'Curl Alternado', grupoMuscular: 'Bíceps'),
  EjercicioMaestro(nombre: 'Curl Martillo', grupoMuscular: 'Bíceps'),
  EjercicioMaestro(nombre: 'Curl Martillo Cruzado', grupoMuscular: 'Bíceps'),
  EjercicioMaestro(nombre: 'Curl Concentrado', grupoMuscular: 'Bíceps'),
  EjercicioMaestro(nombre: 'Curl Predicador', grupoMuscular: 'Bíceps'),
  EjercicioMaestro(nombre: 'Curl Predicador en Máquina', grupoMuscular: 'Bíceps'),
  EjercicioMaestro(nombre: 'Curl en Polea Baja', grupoMuscular: 'Bíceps'),
  EjercicioMaestro(nombre: 'Curl en Polea Alta', grupoMuscular: 'Bíceps'),
  EjercicioMaestro(nombre: 'Curl Unilateral en Polea', grupoMuscular: 'Bíceps'),
  EjercicioMaestro(nombre: 'Curl Inclinado con Mancuernas', grupoMuscular: 'Bíceps'),
  EjercicioMaestro(nombre: 'Curl Spider', grupoMuscular: 'Bíceps'),
  EjercicioMaestro(nombre: 'Curl Zottman', grupoMuscular: 'Bíceps'),
  EjercicioMaestro(nombre: 'Curl Inverso con Barra', grupoMuscular: 'Bíceps'),
  EjercicioMaestro(nombre: 'Curl Inverso en Polea', grupoMuscular: 'Bíceps'),
  EjercicioMaestro(nombre: 'Curl en Máquina Hammer', grupoMuscular: 'Bíceps'),
  EjercicioMaestro(nombre: 'Curl Sentado con Mancuernas', grupoMuscular: 'Bíceps'),
  EjercicioMaestro(nombre: 'Curl Scott', grupoMuscular: 'Bíceps'),
  EjercicioMaestro(nombre: 'Curl Scott en Máquina', grupoMuscular: 'Bíceps'),
  EjercicioMaestro(nombre: 'Curl con Cable y Cuerda', grupoMuscular: 'Bíceps'),
  EjercicioMaestro(nombre: 'Curl Bayesian', grupoMuscular: 'Bíceps'),
  EjercicioMaestro(nombre: 'Curl con Disco', grupoMuscular: 'Bíceps'),
  EjercicioMaestro(nombre: 'Curl 21s', grupoMuscular: 'Bíceps'),
  EjercicioMaestro(nombre: 'Curl Drag', grupoMuscular: 'Bíceps'),
  EjercicioMaestro(nombre: 'Curl Martillo con Cuerda', grupoMuscular: 'Bíceps'),
  EjercicioMaestro(nombre: 'Curl Alternado Giratorio', grupoMuscular: 'Bíceps'),
  EjercicioMaestro(nombre: 'Curl Spider con Barra EZ', grupoMuscular: 'Bíceps'),

  // PIERNA
  EjercicioMaestro(nombre: 'Sentadilla con Barra', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Sentadilla Frontal', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Sentadilla Hack', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Sentadilla en Multipower', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Prensa 45°', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Prensa Horizontal', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Extensión de Cuádriceps', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Curl Femoral Acostado', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Curl Femoral Sentado', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Curl Femoral de Pie', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Peso Muerto Rumano Pierna', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Peso Muerto Sumo', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Zancadas con Mancuernas', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Zancadas con Barra', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Bulgarian Split Squat', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Hip Thrust', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Hip Thrust en Máquina', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Abducción de Cadera', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Aducción de Cadera', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Elevación de Talones de Pie', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Elevación de Talones Sentado', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Pantorrilla en Prensa', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Step Up', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Sentadilla Goblet', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Buenos Días Pierna', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Puente de Glúteo', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Desplantes Caminando', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Sentadilla Sissy', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Curl Nórdico', grupoMuscular: 'Pierna'),
  EjercicioMaestro(nombre: 'Hack Squat Machine', grupoMuscular: 'Pierna'),

  // ABS
  EjercicioMaestro(nombre: 'Crunch Abdominal', grupoMuscular: 'Abs'),
  EjercicioMaestro(nombre: 'Crunch en Máquina', grupoMuscular: 'Abs'),
  EjercicioMaestro(nombre: 'Crunch en Polea', grupoMuscular: 'Abs'),
  EjercicioMaestro(nombre: 'Crunch Declinado', grupoMuscular: 'Abs'),
  EjercicioMaestro(nombre: 'Elevaciones de Piernas', grupoMuscular: 'Abs'),
  EjercicioMaestro(nombre: 'Elevaciones de Rodillas', grupoMuscular: 'Abs'),
  EjercicioMaestro(nombre: 'Elevaciones Colgado', grupoMuscular: 'Abs'),
  EjercicioMaestro(nombre: 'Plancha', grupoMuscular: 'Abs'),
  EjercicioMaestro(nombre: 'Plancha Lateral', grupoMuscular: 'Abs'),
  EjercicioMaestro(nombre: 'Rodillo Abdominal', grupoMuscular: 'Abs'),
];